server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  jwtSecret: MySecretKeyMySecretKeyMySecretKeyMySecretKey
  jwtExpirationInMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG
