server:
  port: 8081


spring:
  application:
    name: api-gateway
#    main:
#      web-application-type: reactive

  cloud:
     gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          # filters:
          #   - StripPrefix=1

        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/account/**
          filters:
            # - StripPrefix=1
            - JwtAuthFilter

        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/transaction/**
          filters:
            # - StripPrefix=1
            - JwtAuthFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"  # Frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example: DEBUG
